# Site Information
site_name: Programming Tech Sharing
site_description: Programming Tech Sharing 是我用来整合知识的一个站点，主要面向编程知识。
site_author: Torres Lei
site_url: https://403unauthorized.github.io

# Repository
repo_name: 'Programming Space'
repo_url: https://github.com/403Unauthorized/403unauthorized.github.io

# Copyright
copyright: 'Copyright &copy; 2021 - 2022 Eng Learning by Torres'

# Contents
nav:
  - 简介:
    - Getting Started: index.md
    - 关于我: about.md
    - 标签: tags.md
  - Java:
    - Java简介: java/index.md
    - Synchronized 学习笔记: java/synchronized.md
    - Volatile 学习笔记: java/volatile.md
    - JVM:
      - Java 垃圾收集器: java/garbage-collector.md
      - JVM 内存区域学习笔记: java/jvm-breakdown.md
    - Spring:
      - Spring Cloud Ribbon: java/spring-cloud-ribbon.md
  - 云原生:
    - 云原生简介: cloud/index.md
    - Golang:
      - Golang基础知识: cloud/golang-basics.md
    - Kubernetes:
      - Kubernetes on CentOS: cloud/kubernetes-on-centos.md
      - 在CentOS上安装K8S: cloud/kubernetes-installation-on-centos.md
  - 算法:
    - 算法系列: algo/index.md
    - LeetCode:
      - Daily:
        - 2022/01/04 - 913. 猫和老鼠: algo/leetcode/daily/2022-01-04.md
        - 2021/01/05 - 1576. 替换所有的问号: algo/leetcode/daily/2022-01-05.md
        - 2022/01/07 - 1614. 括号的最大嵌套深度: algo/leetcode/daily/2022-01-07.md
        - 2022/01/07 - 382. Linked List Random Node: algo/leetcode/daily/2022-01-07-en.md
        - 2022/01/08 - 89. 格雷编码: algo/leetcode/daily/2022-01-08.md
        - 2022/01/09 - 1041. Robot Bounded In Circle: algo/leetcode/daily/2022-01-09-en.md
        - 2022/01/09 - 1629. 按键持续时间最长的键: algo/leetcode/daily/2022-01-09.md
        - 2022/01/10 - 306. 累加数: algo/leetcode/daily/2022-01-10.md
        - 2022/01/11 - 1036. 逃离大迷宫: algo/leetcode/daily/2022-01-11.md
      - String:
        - 8. String to Integer (atoi): algo/leetcode/string/string-to-integer-atoi.md
      - 200. 岛屿数量: algo/leetcode/number-of-islands.md
    - 并查集: algo/union-find.md
    - Manacher算法: algo/manacher-palindrome.md
    - 排序算法:
      - 选择排序: algo/selection-sort.md
      - 插入排序: algo/insertion-sort.md
      


# Plugins
plugins:
  - search
  # - tags:
  #   - tags_file: tags.md

# Theme
theme:
  name: null
  language: zh
  custom_dir: 'mkdocs-material/material'
  static_templates:
    - 404.html
  include_search_page: false
  search_index_only: true
  palette:
    - sheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - content.tabs.link
  icon:
    repo: fontawesome/brands/github-alt
    logo: material/book-education-outline
    admonition:
      note: fontawesome/solid/sticky-note
      abstract: fontawesome/solid/book
      info: fontawesome/solid/info-circle
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/question-circle
      warning: fontawesome/solid/exclamation-triangle
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  favicon: 'favicon.ico'

extra:
  disqus: programming-tech-sharing

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


# Extensions
markdown_extensions:
  - tables
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - attr_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
